### ISSUE TITLE
LO need a font in ttf format with bottom aligned feature. This font is very suitable for LibreOffice.

### ISSUE THREAD

**Issue by rovasiras** [notofonts/old-hungarian-ui#5]
@simoncozens 
LibreOffice needs a good quality font that is aligned to the bottom baseline. The Noto Sans Old Hungarian font is incorrectly center aligned. The ligatures are redundant, the q, w, x and y ligatures are not part of the Latin based Hungarian alphabet, too. This is the position of the Hungarian Academy of Sciences, and it is the principle it follows in developing our spelling system.
Quantum physics ->  kvantumfizika,
Software -> szoftver,
Hardware -> hardver,
nylon -> nejlon, etc...

This font meets the criteria.

**Comment by simoncozens** [comment]
> This is the position of the Hungarian Academy of Sciences

Noto is deliberately an implementation of the Unicode standard, and we are waiting for the Unicode Consortium to confirm various aspects of the Old Hungarian script.

**Comment by rovasiras** [comment]
> > This is the position of the Hungarian Academy of Sciences
> 
> Noto is deliberately an implementation of the Unicode standard, and we are waiting for the Unicode Consortium to confirm various aspects of the Old Hungarian script.

When the ligatures were put into a Unicode document, they were just hand-drawn drafts. Information was missing that the ligature ek+esz was intended to be an "x", the ligature ek+ev was intended to be a "q" (more precisely a "qu"), the ligature i+j was intended to be a "y", the ligature ev+ev was intended to be a "w" and therefore should only be created using ZWJ. for example, the Hungarian word "evvel" is not the same as "ewel". At a conference in the city of Solt in  2012, the need for these was dropped.
[Conference in solt](https://magyarrovas.hu/solti-dontes/)
The ligatures are possibilities, not requirements.

**Comment by rovasiras** [comment]
> > This is the position of the Hungarian Academy of Sciences
> 
> Noto is deliberately an implementation of the Unicode standard, and we are waiting for the Unicode Consortium to confirm various aspects of the Old Hungarian script.

If the Noto project follows the Unicode standard, could you explain me,  why was developed left-to-right section, too? The Unicode standard describes strictly Old Hungarian alphabet is righ-to-left script.

**Comment by rovasiras** [comment]
@simoncozens When will be decided that this font will be published or not?

**Comment by rovasiras** [comment]
@simoncozens I close it
