### ISSUE TITLE
Non-standard LTR letters in the this Old Hngarian repo

### ISSUE THREAD

**Issue by rovasiras** [notofonts/old-hungarian-ui#7]
## Defect Report

The Old Hungarian Unicode standard explicitly states that Old Hungarian writing is RTL writing, yet this repo has LTR letters for writing. These should be taken out of the font.

**Comment by simoncozens** [comment]
It's fine. Fonts will often have glyphs beyond those encoded in Unicode for other uses. There is a long discussion in various Unicode mailing lists about the desire to write Old Hungarian using boustrophedon, for which mirrored glyphs are necessary. They are not doing any harm, so I suggest leaving them there for those who want to use them.

**Comment by rovasiras** [comment]
> It's fine. Fonts will often have glyphs beyond those encoded in Unicode for other uses. There is a long discussion in various Unicode mailing lists about the desire to write Old Hungarian using boustrophedon, for which mirrored glyphs are necessary. They are not doing any harm, so I suggest leaving them there for those who want to use them.

What do you mean by "those who want to use them." The Unicode standard is an IT standard. Whether the Old Hungarian standard letters appear from right to left is independent of the people who use it, and depends more on the laziness of the programmers. Windows 10 and later versions already write right to left, Linux distributions write right to left. There are some applications, such as MuseScore, where they refuse to take the standard into account because their program does not recognize the hu-Hung or ohu-Hung language codes.

**Comment by simoncozens** [comment]
The Unicode standard is a *minimum* for the glyphs in a Noto font. The standard does not specify anything about small caps glyphs, but we add those to some fonts. We add ligatures; we add stylistic sets; we add other functionality to the font that people want to use. This case is the same.

If other applications get this wrong, that's a bug in those applications. Maybe file an issue with them?

**Comment by rovasiras** [comment]
> The Unicode standard is a _minimum_ for the glyphs in a Noto font. The standard does not specify anything about small caps glyphs, but we add those to some fonts. We add ligatures; we add stylistic sets; we add other functionality to the font that people want to use. This case is the same.
> 
> If other applications get this wrong, that's a bug in those applications. Maybe file an issue with them?

It was a file an issue at MuseScore, but nothing happened. We continue this theological debate or do you decide merge the pull request #8 ?

**Comment by simoncozens** [comment]
I don't agree that we should cripple fonts because apps are broken.

**Comment by rovasiras** [comment]
@simoncozens all right.
