### ISSUE TITLE
Missing fonts in binary fonts [ttf,otf]

### ISSUE THREAD

**Issue by kovacshviktor** [notofonts/old-hungarian-ui#9]
It would be necessary to publish ttf and otf files in this repo 
I would like fill up the fork with the requested fonts and ask to receive the main repo.

@simoncozens May I?

**Comment by simoncozens** [comment]
> It would be necessary to publish ttf and otf files in this repo

This is certainly how we used to do things, but these days, we don't store binary artefacts in the repository. The latest builds are available from https://notofonts.github.io/old-hungarian-ui/ and latest release binaries are available from the Noto release site https://notofonts.github.io/

So thank you for your PR, but I am trying to avoid putting built files into the repo.
